# economy
raw_living_space = ((built_land + land_in_progress) * 25) + (barren_land * 15) + (homes * 10)
mod_living_space = (((raw_living_space - homes_bonus) * race_bonus) + homes_bonus) * population_science * honor_population_bonus

peasants_hourly_change = (current_peasants * ((birth_rate + love & peace) * homes_bonus * eowcf * chastity - storms)) - drafted_soldiers - wizards_trained
player.peasants = MIN(mod_living_space, (player.peasants + peasants_hourly_change))

raw_income = (2.75 * employed_peasants) + (2.75/3 * unemployed_peasants) + (0.625 * prisoners) + (banks * 25)
modified_income = raw_income * plague * riots * bank % bonus * income_sci * honor_income_mod * race_mod * personality_mod * dragon * ritual
wages = (((def_specs + off_specs )*0.5) + elites * 0.7) * wage_rate
military_expenses = wages * arms_bonus * race_bonus * max(inspire_army , paladin's_inspiration) * greed
net_income = modified_income - military_expenses
player.gold = MAX(0, player.gold + net_income)

current_population = peasants + soldiers + off_specs + off_specs_in_training + def_specs + def_specs_in_training + elites + elites_in_training + thieves + thieves_in_training + wizards
available_jobs = (completed_buildings - homes) * 25
unfilled_jobs = max ( available_jobs - peasants - rounddown( prisoners / 2 ) , 0 )
employed_peasants = min ( peasants , available_jobs - rounddown ( prisoners / 2 ) )
unemployed_peasants = peasants - employed_peasants
employment_rate = (employed_peasants / peasants) * 100

# food
bushels_eaten = total_population * 0.25 * race_mod * gluttony_mod
base_food_production     = ((farms * 70) * building_efficiency) + (barren_land * 2)
modified_food_production = base_food_production * production_science_mod * fertile_lands_mod * drought_mod
food_remaining = (player.food_stock * 0.99) + modified_food_production - bushels_eaten
player.food = MAX(0, food_remaining)

# military
player.offensive_specialists += pick_next(new_offensive_specialists)
player.defensive_specialists += pick_next(new_defensive_specialists)
player.elites += pick_next(new_elites)

# buildings
player.barren_land += pick_next(barren_land)
player.homes += pick_next(homes)
player.farms += pick_next(farms)
player.mills += pick_next(mills)
player.banks += pick_next(banks)
player.training_grounds += pick_next(training_grounds)
player.armouries += pick_next(armouries)
player.military_barracks += pick_next(military_barracks)
player.forts += pick_next(forts)
player.guard_stations += pick_next(guard_stations)
player.hospitals += pick_next(hospitals)
player.guilds += pick_next(guilds)
player.towers += pick_next(towers)
player.thieves_dens += pick_next(thieves_dens)
player.watch_towers += pick_next(watch_towers)
player.laboratories += pick_next(laboratories)
player.universities += pick_next(universities)
player.dungeons += pick_next(dungeons)

Available Workers = Peasants + ROUNDDOWN ( Prisoners / 2 )
Optimal Workers =  ROUNDDOWN ( Total Jobs * 0.67 )
Jobs Performed          =  MIN ( Available Workers / Optimal Workers , 1 )
Building Efficiency       =  [ (0.5 * (1 + % Jobs Performed)) * Race * Scientists * Dragon ] * Personality
Building Efficiency Change Rate  = TO-DO

# science
Science Bonus = [ MIN( Science Multiplier * Skill points , Cap ) + MAX( 0, Science Multiplier * Skill points - Cap ) * Diminishing Return Factor ] * Race Mod * Personality Mod * Scientific Insights Mod
Skill points = Number of Novices + 1.5 * Number of Graduates + 2 * Number of Professors
Scientists Spawn Rate = 9.5 * Race Mod * Laboratories Effect * Revelation Mod

Percentage Based Buildings = Base Effect * BE * MIN(50%, % of building) * (100% - MIN(50%, % of building))

food_ = Base Effect * Number of Buildings * BE * Scientists

Base Military Efficiency = ( 60 + 40 * ( Effective Wage Rate / 100 ) 0.25 ) * Gangbang Protection * Science Bonus
Change in Effective Wage Rate =  0.05 * (Wage Rate Paid - Effective Wage Rate)
OME = (Base Military Efficiency + Training Ground Bonus + Honor Bonus) * Fanaticism Bonus * Personality Bonus * Onslaught Ritual
DME = (Base Military Efficiency + Forts Bonus) * Minor Protection * Greater Protection * Fanaticism * Plague * Barrier Ritual

gangbang_protection_decay = TO-DO

total_land = built_land + land_in_progress + barren_land


