# ECONOMY
player.peasants = MIN(player.mod_living_space - player.military_population,
                      player.peasants + player.peasants_hourly_change)

player.gold = MAX(0, player.gold + player.net_income)

# FOOD
player.food = MAX(0, player.food_remaining)

# MILITARY
player.offensive_specialists += pick_next(player.offensive_specialists_in_progress)
player.defensive_specialists += pick_next(player.defensive_specialists_in_progress)
player.elites += pick_next(player.elites_in_progress)

# BUILDINGS
player.barren_land += pick_next(player.barren_land_in_progress)
player.homes += pick_next(player.homes_in_progress)
player.farms += pick_next(player.farms_in_progress)
player.mills += pick_next(player.mills_in_progress)
player.banks += pick_next(player.banks_in_progress)
player.training_grounds += pick_next(player.training_grounds_in_progress)
player.armouries += pick_next(player.armouries_in_progress)
player.military_barracks += pick_next(player.military_barracks_in_progress)
player.forts += pick_next(player.forts_in_progress)
player.guard_stations += pick_next(player.guard_stations_in_progress)
player.hospitals += pick_next(player.hospitals_in_progress)
player.guilds += pick_next(player.guilds_in_progress)
player.towers += pick_next(player.towers_in_progress)
player.thieves_dens += pick_next(player.thieves_dens_in_progress)
player.watch_towers += pick_next(player.watch_towers_in_progress)
player.laboratories += pick_next(player.laboratories_in_progress)
player.universities += pick_next(player.universities_in_progress)
player.dungeons += pick_next(player.dungeons_in_progress)

# SCIENCE
# TO-DO: ADD SCIENTISTS

