condition_to_win = ((mod_off * 0.965) / (dst.mod_def * 1.035)) >= 0.97
general_bonus = generals * 0.03
mod_off = raw_offense * (src.ome + general_bonus + src.personality.personality_bonus) * src.race.race_bonus
raw_offense = (src.specialists.offense * offensive_specialists) + (src.elite.offense * elites)

src_offensive_specialists_lost = TO-DO
src_elites_lost = TO-DO

dst_defensive_specialists_lost = TO-DO
dst_elites_lost = TO-DO
dst_troops_lost = dst_defensive_specialists_lost + dst_elites_lost

gains = condition_to_win * MAX ( (dst.total_land *0.2), RANDOM())

src.total_land += gains
dst.total_land -= gains

src.offensive_specialists -= src_offensive_specialists_lost
src.elites -= src_elites_lost

dst.defensive_specialists -= dst_defensive_specialists_lost
dst.elites -= dst_elites_lost
